# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-07-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0011_fcmdevice_fcm_django_registration_id_user_id_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcmdevice',
            name='type',
            field=models.CharField(choices=[('ios', 'ios'), ('android', 'android'),  ('web', 'web')], max_length=10),
        ),
    ]
